# Generated by Django 3.2.11 on 2022-02-04 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=10)),
                ('customer_address', models.CharField(max_length=100)),
                ('customer_contact', models.CharField(max_length=50)),
                ('customer_DOB', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_num', models.CharField(max_length=50)),
                ('account_name', models.CharField(max_length=50)),
                ('balance', models.IntegerField()),
                ('branch_name', models.CharField(max_length=50)),
                ('customer_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crud.customer')),
            ],
        ),
    ]
