# Generated by Django 4.0.1 on 2022-02-13 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_dob', models.DateField(auto_now=True)),
                ('customer_email', models.EmailField(default='non@gmail.com', max_length=254)),
                ('customer_password', models.CharField(max_length=10)),
                ('customer_address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_no', models.CharField(default='P-###', max_length=50)),
                ('product_name', models.CharField(max_length=50)),
                ('product_price', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OMS.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(default='O-###', max_length=50)),
                ('order_date', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('delivery_address', models.CharField(max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OMS.product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OMS.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OMS.customer')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OMS.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OMS.product')),
            ],
        ),
    ]
