# Generated by Django 4.0.1 on 2022-01-29 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD', '0002_alter_students_std_roll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='std_contact',
            field=models.IntegerField(),
        ),
    ]
